#!/usr/bin/env bash
#   ./run.sh /Users/me/code/app [/Users/me/code/lib ...]
#                         # mount these folders at the SAME path in the container, then start
#   ./run.sh --add /path/to/lib [...]
#                         # keep the current folders and add these (first folder stays the working dir)
#   ./run.sh              # start again with the folders from last time
#   ./run.sh --none       # start with no folders mounted
#   ./run.sh --x11        # XQuartz window instead of the browser tab (macOS only)
#   ./run.sh --rebuild    # also pull newer base images (Selkies, Ubuntu, Node) before building
#   ./run.sh --restart    # restart ZCode even if nothing changed
#   ./run.sh --open       # always open a browser tab (default: only when ZCode wasn't already running)
#   ./run.sh --stop       # stop and remove the container (settings/login stay in a volume)
#
# Safe to run any time: starts OrbStack if needed, starts ZCode if it's stopped, rebuilds and
# recreates it only when something changed (packages/, .env, folders, rootfs/), otherwise leaves
# the running session alone. The build runs while the old container keeps serving.
# Folders are recorded in compose.folders.yaml (generated); your own compose tweaks go in compose.override.yaml
# (yours, never touched). ZCode settings/login live in the /config volume.
#
# Runtimes: OrbStack (tested) serves https://zcode.orb.local itself. Any other Docker (untested) gets
# loopback-only ports from compose.docker.yaml: http://localhost:$ZCODE_PORT (default 3000).
# ZCODE_RUNTIME=orbstack|docker in the environment or .env overrides the detection.

set -euo pipefail
caller=$PWD
cd "$(dirname "$0")"

FOLDERS=compose.folders.yaml     # generated by this script
OVERRIDE=compose.override.yaml   # yours: hand-written extras, merged last, never rewritten

# Older versions generated compose.override.yaml. Keep its folders, and set the file aside so
# hand-made additions in it aren't lost to the next regeneration.
if [[ -f $OVERRIDE && ! -f $FOLDERS ]] && head -n 1 "$OVERRIDE" | grep -q '^# Generated by ./run.sh'; then
    cp "$OVERRIDE" "$FOLDERS"
    mv "$OVERRIDE" "$OVERRIDE.bak"
    echo "note: folders moved to $FOLDERS. Your old $OVERRIDE is saved as $OVERRIDE.bak;" >&2
    echo "      copy any custom settings from it into a new $OVERRIDE (that file is yours now)." >&2
fi
service=zcode pull=0 restart=0 open_tab=0 dirs=() none=0 add=0

# A setting from the environment, else from .env (compose reads .env itself; this script needs a few).
setting() {
    local v=${!1:-}
    [[ -n $v ]] || v=$(sed -n "s/^[[:space:]]*$1=//p" .env 2>/dev/null | tail -n 1 | sed -e 's/[[:space:]]#.*//' -e 's/[[:space:]]*$//' -e 's/^["'\'']//' -e 's/["'\'']$//')
    printf '%s' "${v:-${2:-}}"
}
# macOS `open`, Linux `xdg-open`, else print the URL (`open` on Linux is an unrelated tool).
open_url() {
    if [[ $OSTYPE == darwin* ]]; then open "$@"
    elif command -v xdg-open >/dev/null; then xdg-open "$1" >/dev/null 2>&1 &
    else echo "Open in your browser: $1"
    fi
}
for arg in "$@"; do
    case "$arg" in
        --x11) service=zcode-x11 ;;
        --rebuild) pull=1 ;;
        --restart) restart=1 ;;
        --open) open_tab=1 ;;
        --none) none=1 ;;
        --add) add=1 ;;
        --stop) docker compose --profile x11 down; exit ;;
        -*) echo "unknown option: $arg" >&2; exit 2 ;;
        *) dirs+=("$arg") ;;
    esac
done

if (( add )); then
    (( ! none )) || { echo "--add and --none can't be combined" >&2; exit 2; }
    (( ${#dirs[@]} )) || { echo "--add needs at least one folder: ./run.sh --add /path/to/dir" >&2; exit 2; }
fi
# --add: the folders from last time come first, so the working directory stays the same.
kept=0
if (( add )) && [[ -f $FOLDERS ]]; then
    old=()
    while IFS= read -r line; do old+=("$line"); done < <(sed -n 's/.*target: "\(.*\)".*/\1/p' "$FOLDERS")
    kept=${#old[@]}
    dirs=(${old[@]+"${old[@]}"} "${dirs[@]}")
fi

# Resolve, validate and record project folders.
if (( ${#dirs[@]} || none )); then
    mounts="" workdir="" seen=$'\n' i=0
    for arg in ${dirs[@]+"${dirs[@]}"}; do
        i=$((i + 1))
        # Relative paths resolve from where run.sh was invoked; result is absolute, no trailing slash.
        if ! d=$(cd "$caller" && cd "$arg" 2>/dev/null && pwd); then
            # A folder recorded earlier may have been moved or deleted: drop it instead of failing.
            (( i <= kept )) && { echo "dropping missing folder: $arg" >&2; continue; }
            echo "not a directory: $arg" >&2; exit 1
        fi
        case "$d" in
            / | "$HOME" | /Users | /Volumes | /home | /root)
                echo "refusing to mount $d: too broad (it would expose ~/.ssh etc. to the agent)" >&2; exit 1 ;;
            *[\"\$\\]*)
                echo "unsupported character in path: $d" >&2; exit 1 ;;
        esac
        [[ $seen == *$'\n'"$d"$'\n'* ]] && continue   # already listed (e.g. --add of a mounted folder)
        seen+="$d"$'\n'
        mounts+=$'\n'"    - { type: bind, source: \"$d\", target: \"$d\" }"
        : "${workdir:=$d}"
    done
    if (( none )); then
        rm -f "$FOLDERS"
    else
        cat > "$FOLDERS" <<EOF
# Generated by ./run.sh - rerun it with other folders instead of editing.
# Your own compose changes belong in compose.override.yaml, which is merged after this file.
x-projects: &projects$mounts
x-env: &env
  ZCODE_WORKDIR: "$workdir"
  GIT_AUTHOR_NAME: "$(git config --global user.name || true)"
  GIT_AUTHOR_EMAIL: "$(git config --global user.email || true)"
  GIT_COMMITTER_NAME: "$(git config --global user.name || true)"
  GIT_COMMITTER_EMAIL: "$(git config --global user.email || true)"

services:
  zcode:
    volumes: *projects
    environment: *env
  zcode-x11:
    volumes: *projects
    environment: *env
    working_dir: "$workdir"
EOF
    fi
fi

if [[ -f $FOLDERS ]]; then
    echo "Mounted folders (same path in the container):"
    sed -n 's/.*target: "\(.*\)".*/  \1/p' "$FOLDERS"
else
    echo "No folders mounted. Pass one: ./run.sh /Users/you/code/project"
fi

if ! docker info >/dev/null 2>&1; then
    if [[ $OSTYPE == darwin* && -d /Applications/OrbStack.app ]]; then
        echo "Starting OrbStack..."
        open -ga OrbStack
        for _ in {1..120}; do docker info >/dev/null 2>&1 && break; sleep 0.5; done
    fi
    docker info >/dev/null 2>&1 || { echo "Docker isn't responding; start Docker (or OrbStack) first." >&2; exit 1; }
fi

# OrbStack routes zcode.orb.local to the container itself; anything else needs published ports.
runtime=$(setting ZCODE_RUNTIME)
if [[ -z $runtime ]]; then
    if [[ "$(docker context show 2>/dev/null)" == orbstack ]] || docker info --format '{{.OperatingSystem}}' 2>/dev/null | grep -qi orbstack; then
        runtime=orbstack
    else
        runtime=docker
    fi
fi
case "$runtime" in
    orbstack) url=https://zcode.orb.local ;;
    docker)
        url="http://localhost:$(setting ZCODE_PORT 3000)"
        echo "note: plain Docker (not OrbStack) - untested; serving on $url (loopback only)." >&2
        # Bind-mounted files should belong to you, not to whoever has uid 1000 (Linux has no ownership mapping).
        if [[ $OSTYPE == linux* ]]; then
            [[ -n $(setting PUID) ]] || export PUID=$(id -u)
            [[ -n $(setting PGID) ]] || export PGID=$(id -g)
        fi ;;
    *) echo "ZCODE_RUNTIME must be orbstack or docker, not '$runtime'" >&2; exit 2 ;;
esac
files=compose.yaml
[[ -f $FOLDERS ]] && files+=":$FOLDERS"
[[ $runtime == docker ]] && files+=":compose.docker.yaml"
[[ -f $OVERRIDE ]] && files+=":$OVERRIDE"   # last, so your tweaks win
export COMPOSE_FILE=$files

if [[ $service == zcode-x11 ]]; then
    [[ $OSTYPE == darwin* ]] || { echo "--x11 is the macOS XQuartz mode; on Linux use the browser mode." >&2; exit 1; }
    [[ -x /opt/X11/bin/xhost ]] || { echo "XQuartz not found: brew install --cask xquartz" >&2; exit 1; }
    open -a XQuartz
    # OrbStack connects to host.docker.internal from the Mac's loopback, so allowing localhost is enough.
    for _ in {1..50}; do DISPLAY=:0 /opt/X11/bin/xhost +localhost >/dev/null 2>&1 && break; sleep 0.2; done
fi

# What's there now? (container id + whether it runs + which mode)
state() { docker inspect -f '{{.Id}} {{.State.Running}} {{index .Config.Labels "com.docker.compose.service"}}' zcode 2>/dev/null || true; }
read -r before_id before_running before_service <<<"$(state)"

# Both modes use container name "zcode": remove it only when switching modes.
if [[ -n ${before_service:-} && $before_service != "$service" ]]; then
    echo "Switching from $before_service to $service..."
    docker rm -f zcode >/dev/null
    before_id="" before_running=""
fi

(( pull )) && docker compose build --pull "$service"
# Builds first (cached: seconds when nothing changed) while the old container keeps running,
# then recreates it only if the image, settings or folders differ; starts it if stopped.
docker compose up -d --build --remove-orphans "$service"

read -r after_id _ _ <<<"$(state)"
if [[ -z ${before_id:-} ]]; then
    status=started; open_tab=1
elif [[ $before_id != "$after_id" ]]; then
    status="restarted with changes applied"
elif [[ ${before_running:-} != true ]]; then
    status=started; open_tab=1
elif (( restart )); then
    docker compose restart "$service" >/dev/null
    status=restarted
else
    status="already running and up to date"
fi

if [[ $service == zcode ]]; then
    if [[ $status != "already running and up to date" ]]; then
        echo "Waiting for $url ..."
        for _ in {1..240}; do curl -fsk -o /dev/null "$url" && break; sleep 0.5; done
    fi
    # An open tab reconnects by itself after a restart; a second tab would double the encoding cost.
    if (( open_tab )); then
        open_url "$url"
    elif [[ $status == "already running and up to date" ]]; then
        echo "Your tab is still live at $url (./run.sh --open for a new one)."
    else
        echo "Your open tab reconnects by itself (or visit $url; --open forces a new tab)."
    fi
fi

echo ""
echo "ZCode: $status."
echo "Not logged in yet? Click Login in ZCode, then run ./login.sh"
